### ISSUE TITLE
[REVIEW] 审核/整理/更新“简介”

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#1109]
- [ ] source/intro/citation.rst @seisman #1181
- [ ] source/intro/index.rst @seisman
- [ ] source/intro/overview.rst @seisman #1180
- [ ] source/intro/resources.rst
- [ ] ~~source/intro/versions.rst~~ @seisman #1182 #1184

https://github.com/gmt-china/GMT_docs/pull/1186
