### ISSUE TITLE
[REVIEW] 审核/整理/更新“安装”一章

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#1110]
- [ ] source/install/UnixTools.zip
- [ ] source/install/build-source-unix.rst @seisman #1198
- [ ] source/install/build-source-windows.rst @seisman #1200
- [ ] source/install/centos.rst @seisman #1196
- [ ] source/install/conda.rst @seisman #1192
- [ ] source/install/fedora.rst @seisman #1193
- [ ] source/install/index.rst @seisman #1202
- [ ] source/install/macOS.rst @seisman #1190
- [ ] source/install/ubuntu-debian.rst @seisman #1197
- [ ] source/install/windows.rst @seisman #1199

**Comment by seisman** [comment]
已完成审核。Windows 安装指南以及 UnixTools 的去留问题在 https://github.com/gmt-china/GMT_docs/issues/1203 中进一步讨论。
