### ISSUE TITLE
[REVIEW] 审核/整理/更新“地学数据集”一章

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#1121]
- [x] source/dataset/PB2002/PB2002.sh @seisman #1208
- [x] source/dataset/PB2002/PB2002_boundaries.dig.txt @seisman #1208
- [x] source/dataset/PB2002/PB2002_plates.dig.txt @seisman #1208
- [x] source/dataset/PB2002/index.rst @seisman #1208
- [ ] source/dataset/dcw/dcw-countries.txt
- [ ] source/dataset/dcw/dcw-states.txt
- [ ] source/dataset/dcw/dcw.png
- [ ] source/dataset/dcw/index.rst
- [ ] ~~source/dataset/earth-age.rst~~
- [ ] ~~source/dataset/earth-faa.rst~~
- [ ] ~~source/dataset/earth-geoid.rst~~
- [ ] ~~source/dataset/earth-images.rst~~
- [ ] ~~source/dataset/earth-mag.rst~~
- [ ] ~~source/dataset/earth-mask.rst~~
- [ ] ~~source/dataset/earth-relief.rst~~
- [ ] source/dataset/gadm/gadm_level0.pdf
- [ ] source/dataset/gadm/gadm_level0.png
- [ ] source/dataset/gadm/gadm_level0.sh
- [ ] source/dataset/gadm/gadm_level1.pdf
- [ ] source/dataset/gadm/gadm_level1.png
- [ ] source/dataset/gadm/gadm_level1.sh
- [ ] source/dataset/gadm/gadm_level2.pdf
- [ ] source/dataset/gadm/gadm_level2.png
- [ ] source/dataset/gadm/gadm_level2.sh
- [ ] source/dataset/gadm/index.rst
- [x] source/dataset/global_tectonics/boundaries.sh. @seisman #1211
- [x] source/dataset/global_tectonics/global_gprv.sh @seisman #1211
- [x] source/dataset/global_tectonics/index.rst @seisman #1211
- [x] source/dataset/global_tectonics/plates.sh @seisman #1211
- [x] source/dataset/gshhg.jpg @seisman #1209
- [x] source/dataset/gshhg.rst @seisman #1209
- [ ] source/dataset/index.rst
- [ ] source/dataset/usage.rst
