### ISSUE TITLE
[REVIEW] 审核/整理/更新“连续集成”相关文件

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#1132]
- [x] ~~.github/ISSUE_TEMPLATE/issue.md~~ @seisman @ZMAlt  https://github.com/gmt-china/GMT_docs/pull/1135
- [x] .github/ISSUE_TEMPLATE/release-checklist.md @seisman @ZMAlt #1141
- [x] .github/dependabot.yml @seisman @ZMAlt  #1134
- [x] .github/workflows/cache-data.yml @seisman 
- [x] .github/workflows/check-links.yml @seisman 
- [x] .github/workflows/compress-images.yml @seisman
- [x] .github/workflows/deploy.yml @seisman @ZMAlt  #1142
- [x] .gitignore @seisman 
- [x] .readthedocs.yaml @seisman
- [x] Makefile @seisman 
- [x] README.md @seisman @ZMAlt  #1139
- [x] environment.yml @seisman 
- [x] ~~requirements.txt~~ @seisman @ZMAlt  #1136
- [x] scripts/setup-ci.sh @seisman @core-man #1138
- [x] scripts/setup-latex.sh @seisman @core-man #1137

**Comment by seisman** [comment]
@gmt-china/contributors I've reviewed all files listed in the issue and made some updated when possible.

After merging all the linked PRs, these files all look good to me, except the deleted issue template `release-checklist.md`, which will be revised when we make the 6.4 release in issue https://github.com/gmt-china/GMT_docs/issues/1140.

Please review these files if you have time. Otherwise I'll close the issue next Monday.

**Comment by ZMAlt** [comment]
没有问题。
