### ISSUE TITLE
中文社区图库迁移至中文文档

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#302]
自 #293 开始，我们逐渐迁移[社区图库](https://gmt-china.org/gallery)。迁移每个例子至中文手册后，即可将社区图库地址重定向新地址 (参考 https://github.com/gmt-china/gmt-china.org/pull/182)

## 地形起伏

- [x] [ex010：中国大陆地区地形图](https://gmt-china.org/example/ex010/)（@wangliang1989 决定不再迁移）
- [x] [ex021：夏威夷岛地形起伏图](https://gmt-china.org/example/ex021/)（已经在 https://github.com/gmt-china/gmt-china.org/pull/249 删除）
- [ ] [ex024：GMT绘制三维地形轨迹图](https://gmt-china.org/example/ex024/)
- [ ] [ex027：三维地形图](https://gmt-china.org/example/ex027/) (#476)

## 地震活动性

- [x] [ex001：震源机制分布图](https://gmt-china.org/example/ex001/) (https://github.com/gmt-china/gmt-china.org/pull/203 by @CovMat)
- [x] [ex011：事件相对台站的震中距方位角分布图](https://gmt-china.org/example/ex011/) (#415 & https://github.com/gmt-china/gmt-china.org/pull/208 by @CovMat)
- [ ] [ex012：M-T图](https://gmt-china.org/example/ex012/) (#374)
- [ ] [ex014：指定测线的地震剖面图](https://gmt-china.org/example/ex014/) (~~related to https://github.com/gmt-china/gmt-china.org/issues/78~~) (#476)
- [ ] [ex019：含地形起伏的地震剖面图](https://gmt-china.org/example/ex019/) (#476)
- [ ] [ex026：俯冲带地震分布](https://gmt-china.org/example/ex026/) (#476)

##  中国地理空间数据

- [x] [ex003：中国国界、省界及十段线](https://gmt-china.org/example/ex003/) (#343 & https://github.com/gmt-china/gmt-china.org/pull/188 by @CovMat)
- [x] [ex004：中国省会城市分布图](https://gmt-china.org/example/ex004/) (REMOVED)
- [x] [ex005：中国地震区域划分](https://gmt-china.org/example/ex005/) (REMOVED)
- [x] [ex006：中国铁路线](https://gmt-china.org/example/ex006/) (REMOVED)
- [x] [ex007：中国断层数据](https://gmt-china.org/example/ex007/) (https://github.com/gmt-china/gmt-china.org/pull/188 by @CovMat)
- [x] [ex008：中国一级河流数据](https://gmt-china.org/example/ex008/) (REMOVED)
- [x] [ex016：中国大陆及周边活动地块分布图](https://gmt-china.org/example/ex016/) (#347 by @CovMat | https://github.com/gmt-china/gmt-china.org/pull/191 by @core-man)

##  未分类

- [x] [ex002：绘制地球内部主要界面](https://gmt-china.org/example/ex002/) (#293 by @wangliang1989 | https://github.com/gmt-china/gmt-china.org/pull/182 by @seisman ）
- [x] [ex009：晨昏线及太阳位置](https://gmt-china.org/example/ex009/) (https://github.com/gmt-china/gmt-china.org/pull/205 by @CovMat)
- [ ] [ex013：等高线图和剖面图](https://gmt-china.org/example/ex013/) (#476, #468, #166)
- [ ] [ex015：GPS速度场](https://gmt-china.org/example/ex015/)
- [ ] [ex017：矢量及应力应变张量](https://gmt-china.org/example/ex017/)
- [x] [ex018：自定义符号](https://gmt-china.org/example/ex018/) (#356 & https://github.com/gmt-china/gmt-china.org/pull/200 by @CovMat)
- [ ] [ex020：速度模型](https://gmt-china.org/example/ex020/)
- [x] [ex022：地球化学三角图解的绘制](https://gmt-china.org/example/ex022/) (https://github.com/gmt-china/GMT_docs/pull/413 by @CovMat)
- [x] [ex023：图中图](https://gmt-china.org/example/ex023/) (https://github.com/gmt-china/gmt-china.org/pull/202 by @CovMat )
- [ ] [ex025：InSAR形变速率场](https://gmt-china.org/example/ex025/)

**Comment by core-man** [comment]
After #293, we could remove [ex002](https://github.com/gmt-china/gmt-china.org/tree/master/content/example/ex002) or add a new link on the original post.

**Comment by CovMat** [comment]
因为做视频教程的时候，是用社区网站的图库做例子，直接删除会给看视频的新手造成迷惑。

最好能清空页面的内容，留下一个链接，例如：
```
本例已迁移至 XXXX
```
之类的

**Comment by core-man** [comment]
> 因为做视频教程的时候，是用社区网站的图库做例子，直接删除会给看视频的新手造成迷惑。
> 
> 最好能保留整体预览的页面，每个例子里面清空页面的内容，留下一个链接，例如：
> 
> ```
> 本例已迁移至 XXXX
> ```
> 
> 之类的

也可以设置页面直接跳转至最新网址

**Comment by core-man** [comment]
我将社区图库做了一个列表在上面，并且会实时更新最新进展。某一个例子完成迁移后，会打上勾。目前迁移中，我觉得会有两个问题：
- 某些例子可能不需要再维护和迁移
- 某几个例子可能可以合并迁移至同一个图库下
- 图库编号，目前社区最大编号是27。我们是否需要保留原有编号，我的答案是 yes。

**Comment by core-man** [comment]
迁移或者重定向社区图库和博客的时候，建议最好同时看看中文手册的对应例子是否需要做一定的更新。

**Comment by CovMat** [comment]
讨论一下
https://gmt-china.org/example/ex027/ 是否直接放弃，页面重定向到 https://docs.gmt-china.org/6.2/examples/ex029/

@seisman  @core-man

**Comment by seisman** [comment]
> 讨论一下
> [gmt-china.org/example/ex027](https://gmt-china.org/example/ex027/) 是否直接放弃，页面重定向到 [docs.gmt-china.org/6.2/examples/ex029](https://docs.gmt-china.org/6.2/examples/ex029/)
> 
> @seisman @core-man

我觉得没有必要。

**Comment by core-man** [comment]
以下例子都涉及到提取地形的2D剖面，我觉得可以简化为一个2D地形剖面提取和绘制的图例，2D 地形剖面还是听常用。单独的27没必要维护了。
- [ ] [ex027：三维地形图](https://gmt-china.org/example/ex027/)
- [ ] [ex014：指定测线的地震剖面图](https://gmt-china.org/example/ex014/)
- [ ] [ex019：含地形起伏的地震剖面图](https://gmt-china.org/example/ex019/)
- [ ] [ex026：俯冲带地震分布](https://gmt-china.org/example/ex026/)

此外，这三个例子又涉及到地震活动性2D剖面，我觉得可以简化为一个2D地震活动性剖面的提取和绘制图例：
- [ ] [ex014：指定测线的地震剖面图](https://gmt-china.org/example/ex014/)
- [ ] [ex019：含地形起伏的地震剖面图](https://gmt-china.org/example/ex019/)
- [ ] [ex026：俯冲带地震分布](https://gmt-china.org/example/ex026/)

**Comment by core-man** [comment]
> 以下例子都涉及到提取地形的2D剖面，我觉得可以简化为一个2D地形剖面提取和绘制的图例，2D 地形剖面还是挺常用 (see [#354 (comment)](https://github.com/gmt-china/GMT_docs/pull/354#issuecomment-855641623)) 。单独的27没必要维护了，至于是重定向到29，还是未来可能的2d剖面例子，我觉得可以是29。
> 
> * [ex027：三维地形图](https://gmt-china.org/example/ex027/)
> * [ex014：指定测线的地震剖面图](https://gmt-china.org/example/ex014/)
> * [ex019：含地形起伏的地震剖面图](https://gmt-china.org/example/ex019/)
> * [ex026：俯冲带地震分布](https://gmt-china.org/example/ex026/)
> * [ex013：等高线图和剖面图](https://gmt-china.org/example/ex013/)
> 
> 此外，这三个例子又涉及到地震活动性2D剖面，我觉得可以简化为一个2D地震活动性剖面的提取和绘制图例：
> 
> * [ex014：指定测线的地震剖面图](https://gmt-china.org/example/ex014/)
> * [ex019：含地形起伏的地震剖面图](https://gmt-china.org/example/ex019/)
> * [ex026：俯冲带地震分布](https://gmt-china.org/example/ex026/)

FYI. 鉴于这些图例很常用，我提交了一个 #476

**Comment by core-man** [comment]
Closed since we will complete the migration in individual issues.
