### ISSUE TITLE
Add a release checklist

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#314]
We freeze the old version of the documentation when a new GMT version is released. For example, when GMT 6.2.0 is released, we freeze the v6.1 documentation, make the v6.1 release, and bump the GMT version to 6.2.0. 

We need a checklist to make sure that the upgrading from 6.1.1 to 6.2.0 is smooth. 

Here is a preliminary list of files that need to be changed:

- [ ] `.github/workflows/cache-data.yml` (#396 by @core-man)
- [ ] `.github/workflows/deploy.yml` (#396 by @core-man)
- [ ] `.github/workflows/preview-pr.yml` (#396 by @core-man)
- [ ] `source/intro/overview.rst` (#397 by @core-man)
- [ ] `source/install/*.rst` (#399 by @core-man)
- [ ] `source/tutorial/get-started/*` (#398 by @core-man) 
- [ ] Add the version number to `source/_static/version_switch.js` (#400 by @seisman)
- [ ] Update the version number in `README.md` (#402 by @core-man)
- [ ] Update the version number in `source/conf.py` (#401 by @seisman)

We may learn more lessons when working on PR #313.

**Comment by core-man** [comment]
We may create a 6.2 branch to submit PRs to this branch before we finally merge it into the master?

**Comment by seisman** [comment]
The 2nd way is much easier.
