### ISSUE TITLE
更新每章首页？

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#371]
自 #345 #362 #366 #368 我们提出修改每一章的 index 页面，事实上很多章的 index 都需要更新，以便读者阅览后快速知道每章的主要内容。有的干脆没有总结，有的总结的比较混乱。

为了减少不必要的issue数目，在此统一汇总每章 index 页面的更新，大家可以认领和修改以下列表。如果不确定是否需要修改，或者如何修改，可以在此 issue 下讨论。

## GMT 入门
- [x] [简介](https://docs.gmt-china.org/latest/intro/#) (#486 by @core-man)
- [x] [安装](https://docs.gmt-china.org/latest/install/) (#487 by @core-man)
- [x] [版本迁移 ](https://docs.gmt-china.org/latest/migrating/) (#482 by @core-man)
- [x] [入门教程](https://docs.gmt-china.org/latest/tutorial/started/) (#461 by @core-man)
- [x] [进阶教程](https://docs.gmt-china.org/latest/tutorial/advanced/) (#461 by @core-man)

## 绘图实例
- [x] [绘图实例](https://docs.gmt-china.org/latest/examples/#) (#481 by @core-man)

## GMT 进阶
- [x] [GMT基础](https://docs.gmt-china.org/latest/basis/) (#479 by @core-man)
- [x] [表数据](https://docs.gmt-china.org/latest/table/) (#484 by @core-man)
- [x] [网格文件](https://docs.gmt-china.org/latest/grid/) (#488 by @core-man)
- [x] [CPT文件](https://docs.gmt-china.org/latest/cpt/) (#483 by @core-man)
- [x] [标准选项](https://docs.gmt-china.org/latest/option/) (#490 by @core-man)
- [x] [地图投影](https://docs.gmt-china.org/latest/proj/) (#368 by @core-man)
- [x] [配置参数](https://docs.gmt-china.org/latest/conf/) (#491 by @core-man)
- [x] [地学数据集](https://docs.gmt-china.org/latest/dataset/) (#362 by @core-man)
- [x] [中国地理空间数据集](https://docs.gmt-china.org/latest/dataset-CN/) (#345 by @CovMat)
- [x] [中文支持](https://docs.gmt-china.org/latest/chinese/) (#485 by @core-man)
- [x] [API](https://docs.gmt-china.org/latest/api/) (#478 by @core-man)
- [ ] [模块手册](https://docs.gmt-china.org/latest/module/) 
  - [x] #366 by @seisman
  - [ ] #443
  - [ ] #440

**Comment by seisman** [comment]
你的意思是每章的 index 页面加上几句话介绍这一章是干嘛的？

**Comment by core-man** [comment]
> 你的意思是每章的 index 页面加上几句话介绍这一章是干嘛的？

差不多吧
