### ISSUE TITLE
更新 source/images 图片

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#536]
## 问题描述

`source/images` 包含了一些通用图片，如 
```
$ ls source/images
combined_logo.pdf  GMT6_Summit_2019.jpg           GMT_patterns.pdf     GMT_RGBchart_a4.png      GMT_stand+_iso+.pdf      GMT_symbol_dingbats.png
combined_logo.png  GMT_chinese.png                GMT_patterns.png     GMT_RGBchart_letter.pdf  GMT_stand+_iso+.png      gshhg.jpg
dcw.png            GMT_chinese_windows_fonts.png  GMT_RGBchart_a4.pdf  GMT_RGBchart_letter.png  GMT_symbol_dingbats.pdf  Matlab_path.png
```

这里有些图片是否可以直接放在对应章节下？例如，
- [x] `GMT_patterns.*`, `GMT_stand+_iso+.*`, `GMT_stand+_iso+.*` (#545 by @seisman)
- [x] `Matlab_path.png` (#565 by @core-man)
- [x] `dcw.png`, `gshhg.jpg` (#566 by @core-man)
- [x] `combined_logo.*` (https://github.com/gmt-china/logo/pull/5 by @core-man)
- [x] `GMT6_Summit_2019.jpg` (#564 by @core-man)
- [x] `GMT_RGBchart_a4.*`, `GMT_RGBchart_letter.*` (#568 by @core-man)
- [x] `GMT_chinese_windows_fonts.png` (#567 by @core-man)

以上列表会持续更新。建议每次单独移动一个章节对应的图片。

**Comment by seisman** [comment]
可以

**Comment by core-man** [comment]
建议先处理 #537， 因为有些文件与 `source/scripts` 里的脚本有关，需要一块处理。
